# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: symbol.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csymbol.proto\x12\x03srm\"\x82\x01\n\x0eReserveRequest\x12\x0c\n\x04repo\x18\x01 \x01(\t\x12\x0e\n\x06\x62ranch\x18\x02 \x01(\t\x12\x0f\n\x07\x66q_name\x18\x03 \x01(\t\x12\x0c\n\x04kind\x18\x04 \x01(\t\x12\x11\n\tfile_path\x18\x05 \x01(\t\x12\x0f\n\x07plan_id\x18\x06 \x01(\t\x12\x0f\n\x07ttl_sec\x18\x07 \x01(\x05\"D\n\x0cReserveReply\x12\x10\n\x08lease_id\x18\x01 \x01(\x03\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x12\n\nexpires_at\x18\x03 \x01(\t\"4\n\x0c\x43laimRequest\x12\x10\n\x08lease_id\x18\x01 \x01(\x03\x12\x12\n\ncommit_sha\x18\x02 \x01(\t\"\x1c\n\nClaimReply\x12\x0e\n\x06status\x18\x01 \x01(\t\">\n\rLookupRequest\x12\x0c\n\x04repo\x18\x01 \x01(\t\x12\x0e\n\x06\x62ranch\x18\x02 \x01(\t\x12\x0f\n\x07\x66q_name\x18\x03 \x01(\t\"D\n\x0bLookupReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\tfile_path\x18\x02 \x01(\t\x12\x12\n\ncommit_sha\x18\x03 \x01(\t2\xa0\x01\n\x0eSymbolRegistry\x12\x31\n\x07Reserve\x12\x13.srm.ReserveRequest\x1a\x11.srm.ReserveReply\x12+\n\x05\x43laim\x12\x11.srm.ClaimRequest\x1a\x0f.srm.ClaimReply\x12.\n\x06Lookup\x12\x12.srm.LookupRequest\x1a\x10.srm.LookupReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'symbol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESERVEREQUEST']._serialized_start=22
  _globals['_RESERVEREQUEST']._serialized_end=152
  _globals['_RESERVEREPLY']._serialized_start=154
  _globals['_RESERVEREPLY']._serialized_end=222
  _globals['_CLAIMREQUEST']._serialized_start=224
  _globals['_CLAIMREQUEST']._serialized_end=276
  _globals['_CLAIMREPLY']._serialized_start=278
  _globals['_CLAIMREPLY']._serialized_end=306
  _globals['_LOOKUPREQUEST']._serialized_start=308
  _globals['_LOOKUPREQUEST']._serialized_end=370
  _globals['_LOOKUPREPLY']._serialized_start=372
  _globals['_LOOKUPREPLY']._serialized_end=440
  _globals['_SYMBOLREGISTRY']._serialized_start=443
  _globals['_SYMBOLREGISTRY']._serialized_end=603
# @@protoc_insertion_point(module_scope)
