# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: symbol.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

from . import symbol_pb2


class SymbolRegistryBase(abc.ABC):

    @abc.abstractmethod
    async def Reserve(self, stream: 'grpclib.server.Stream[symbol_pb2.ReserveRequest, symbol_pb2.ReserveReply]') -> None:
        pass

    @abc.abstractmethod
    async def Claim(self, stream: 'grpclib.server.Stream[symbol_pb2.ClaimRequest, symbol_pb2.ClaimReply]') -> None:
        pass

    @abc.abstractmethod
    async def Lookup(self, stream: 'grpclib.server.Stream[symbol_pb2.LookupRequest, symbol_pb2.LookupReply]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/srm.SymbolRegistry/Reserve': grpclib.const.Handler(
                self.Reserve,
                grpclib.const.Cardinality.UNARY_UNARY,
                symbol_pb2.ReserveRequest,
                symbol_pb2.ReserveReply,
            ),
            '/srm.SymbolRegistry/Claim': grpclib.const.Handler(
                self.Claim,
                grpclib.const.Cardinality.UNARY_UNARY,
                symbol_pb2.ClaimRequest,
                symbol_pb2.ClaimReply,
            ),
            '/srm.SymbolRegistry/Lookup': grpclib.const.Handler(
                self.Lookup,
                grpclib.const.Cardinality.UNARY_UNARY,
                symbol_pb2.LookupRequest,
                symbol_pb2.LookupReply,
            ),
        }


class SymbolRegistryStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Reserve = grpclib.client.UnaryUnaryMethod(
            channel,
            '/srm.SymbolRegistry/Reserve',
            symbol_pb2.ReserveRequest,
            symbol_pb2.ReserveReply,
        )
        self.Claim = grpclib.client.UnaryUnaryMethod(
            channel,
            '/srm.SymbolRegistry/Claim',
            symbol_pb2.ClaimRequest,
            symbol_pb2.ClaimReply,
        )
        self.Lookup = grpclib.client.UnaryUnaryMethod(
            channel,
            '/srm.SymbolRegistry/Lookup',
            symbol_pb2.LookupRequest,
            symbol_pb2.LookupReply,
        )
