# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: git_adapter.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'git_adapter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11git_adapter.proto\x12\x03git\"\x13\n\x04Repo\x12\x0b\n\x03url\x18\x01 \x01(\t\"7\n\x0f\x43heckoutRequest\x12\x17\n\x04repo\x18\x01 \x01(\x0b\x32\t.git.Repo\x12\x0b\n\x03ref\x18\x02 \x01(\t\"4\n\rCheckoutReply\x12\x0f\n\x07workdir\x18\x01 \x01(\t\x12\x12\n\ncommit_sha\x18\x02 \x01(\t\"E\n\x0fReadFileRequest\x12\x17\n\x04repo\x18\x01 \x01(\x0b\x32\t.git.Repo\x12\x0b\n\x03ref\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\" \n\rReadFileReply\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"B\n\x0b\x44iffRequest\x12\x17\n\x04repo\x18\x01 \x01(\x0b\x32\t.git.Repo\x12\x0c\n\x04\x62\x61se\x18\x02 \x01(\t\x12\x0c\n\x04head\x18\x03 \x01(\t\"!\n\tDiffReply\x12\x14\n\x0cunified_diff\x18\x01 \x01(\t\"B\n\x0c\x42lameRequest\x12\x17\n\x04repo\x18\x01 \x01(\x0b\x32\t.git.Repo\x12\x0b\n\x03ref\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\"\x1d\n\nBlameReply\x12\x0f\n\x07\x63ommits\x18\x01 \x03(\t2\xcf\x01\n\nGitAdapter\x12\x34\n\x08\x43heckout\x12\x14.git.CheckoutRequest\x1a\x12.git.CheckoutReply\x12\x34\n\x08ReadFile\x12\x14.git.ReadFileRequest\x1a\x12.git.ReadFileReply\x12(\n\x04\x44iff\x12\x10.git.DiffRequest\x1a\x0e.git.DiffReply\x12+\n\x05\x42lame\x12\x11.git.BlameRequest\x1a\x0f.git.BlameReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'git_adapter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REPO']._serialized_start=26
  _globals['_REPO']._serialized_end=45
  _globals['_CHECKOUTREQUEST']._serialized_start=47
  _globals['_CHECKOUTREQUEST']._serialized_end=102
  _globals['_CHECKOUTREPLY']._serialized_start=104
  _globals['_CHECKOUTREPLY']._serialized_end=156
  _globals['_READFILEREQUEST']._serialized_start=158
  _globals['_READFILEREQUEST']._serialized_end=227
  _globals['_READFILEREPLY']._serialized_start=229
  _globals['_READFILEREPLY']._serialized_end=261
  _globals['_DIFFREQUEST']._serialized_start=263
  _globals['_DIFFREQUEST']._serialized_end=329
  _globals['_DIFFREPLY']._serialized_start=331
  _globals['_DIFFREPLY']._serialized_end=364
  _globals['_BLAMEREQUEST']._serialized_start=366
  _globals['_BLAMEREQUEST']._serialized_end=432
  _globals['_BLAMEREPLY']._serialized_start=434
  _globals['_BLAMEREPLY']._serialized_end=463
  _globals['_GITADAPTER']._serialized_start=466
  _globals['_GITADAPTER']._serialized_end=673
# @@protoc_insertion_point(module_scope)
