# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import git_adapter_pb2 as git__adapter__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in git_adapter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GitAdapterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Checkout = channel.unary_unary(
                '/git.GitAdapter/Checkout',
                request_serializer=git__adapter__pb2.CheckoutRequest.SerializeToString,
                response_deserializer=git__adapter__pb2.CheckoutReply.FromString,
                _registered_method=True)
        self.ReadFile = channel.unary_unary(
                '/git.GitAdapter/ReadFile',
                request_serializer=git__adapter__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=git__adapter__pb2.ReadFileReply.FromString,
                _registered_method=True)
        self.Diff = channel.unary_unary(
                '/git.GitAdapter/Diff',
                request_serializer=git__adapter__pb2.DiffRequest.SerializeToString,
                response_deserializer=git__adapter__pb2.DiffReply.FromString,
                _registered_method=True)
        self.Blame = channel.unary_unary(
                '/git.GitAdapter/Blame',
                request_serializer=git__adapter__pb2.BlameRequest.SerializeToString,
                response_deserializer=git__adapter__pb2.BlameReply.FromString,
                _registered_method=True)


class GitAdapterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Checkout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Diff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Blame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GitAdapterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Checkout': grpc.unary_unary_rpc_method_handler(
                    servicer.Checkout,
                    request_deserializer=git__adapter__pb2.CheckoutRequest.FromString,
                    response_serializer=git__adapter__pb2.CheckoutReply.SerializeToString,
            ),
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=git__adapter__pb2.ReadFileRequest.FromString,
                    response_serializer=git__adapter__pb2.ReadFileReply.SerializeToString,
            ),
            'Diff': grpc.unary_unary_rpc_method_handler(
                    servicer.Diff,
                    request_deserializer=git__adapter__pb2.DiffRequest.FromString,
                    response_serializer=git__adapter__pb2.DiffReply.SerializeToString,
            ),
            'Blame': grpc.unary_unary_rpc_method_handler(
                    servicer.Blame,
                    request_deserializer=git__adapter__pb2.BlameRequest.FromString,
                    response_serializer=git__adapter__pb2.BlameReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'git.GitAdapter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('git.GitAdapter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GitAdapter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Checkout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/git.GitAdapter/Checkout',
            git__adapter__pb2.CheckoutRequest.SerializeToString,
            git__adapter__pb2.CheckoutReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/git.GitAdapter/ReadFile',
            git__adapter__pb2.ReadFileRequest.SerializeToString,
            git__adapter__pb2.ReadFileReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Diff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/git.GitAdapter/Diff',
            git__adapter__pb2.DiffRequest.SerializeToString,
            git__adapter__pb2.DiffReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Blame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/git.GitAdapter/Blame',
            git__adapter__pb2.BlameRequest.SerializeToString,
            git__adapter__pb2.BlameReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
