# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'rag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trag.proto\x12\x03rag\"6\n\x0bSearchQuery\x12\r\n\x05query\x18\x01 \x01(\t\x12\t\n\x01k\x18\x02 \x01(\x05\x12\r\n\x05\x61lpha\x18\x03 \x01(\x02\":\n\x06\x44ocRef\x12\x10\n\x08point_id\x18\x01 \x01(\t\x12\x0f\n\x07snippet\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x02\"+\n\x0bSearchReply\x12\x1c\n\x07results\x18\x01 \x03(\x0b\x32\x0b.rag.DocRef\"2\n\x0eSnippetRequest\x12\x10\n\x08point_id\x18\x01 \x01(\t\x12\x0e\n\x06radius\x18\x02 \x01(\x05\"\x1c\n\x0cSnippetReply\x12\x0c\n\x04text\x18\x01 \x01(\t2s\n\nRagService\x12\x32\n\x0cHybridSearch\x12\x10.rag.SearchQuery\x1a\x10.rag.SearchReply\x12\x31\n\x07Snippet\x12\x13.rag.SnippetRequest\x1a\x11.rag.SnippetReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHQUERY']._serialized_start=18
  _globals['_SEARCHQUERY']._serialized_end=72
  _globals['_DOCREF']._serialized_start=74
  _globals['_DOCREF']._serialized_end=132
  _globals['_SEARCHREPLY']._serialized_start=134
  _globals['_SEARCHREPLY']._serialized_end=177
  _globals['_SNIPPETREQUEST']._serialized_start=179
  _globals['_SNIPPETREQUEST']._serialized_end=229
  _globals['_SNIPPETREPLY']._serialized_start=231
  _globals['_SNIPPETREPLY']._serialized_end=259
  _globals['_RAGSERVICE']._serialized_start=261
  _globals['_RAGSERVICE']._serialized_end=376
# @@protoc_insertion_point(module_scope)
