# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import symbol_pb2 as symbol__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in symbol_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SymbolRegistryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Reserve = channel.unary_unary(
                '/srm.SymbolRegistry/Reserve',
                request_serializer=symbol__pb2.ReserveRequest.SerializeToString,
                response_deserializer=symbol__pb2.ReserveReply.FromString,
                _registered_method=True)
        self.Claim = channel.unary_unary(
                '/srm.SymbolRegistry/Claim',
                request_serializer=symbol__pb2.ClaimRequest.SerializeToString,
                response_deserializer=symbol__pb2.ClaimReply.FromString,
                _registered_method=True)
        self.Lookup = channel.unary_unary(
                '/srm.SymbolRegistry/Lookup',
                request_serializer=symbol__pb2.LookupRequest.SerializeToString,
                response_deserializer=symbol__pb2.LookupReply.FromString,
                _registered_method=True)


class SymbolRegistryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Reserve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Claim(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Lookup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SymbolRegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Reserve': grpc.unary_unary_rpc_method_handler(
                    servicer.Reserve,
                    request_deserializer=symbol__pb2.ReserveRequest.FromString,
                    response_serializer=symbol__pb2.ReserveReply.SerializeToString,
            ),
            'Claim': grpc.unary_unary_rpc_method_handler(
                    servicer.Claim,
                    request_deserializer=symbol__pb2.ClaimRequest.FromString,
                    response_serializer=symbol__pb2.ClaimReply.SerializeToString,
            ),
            'Lookup': grpc.unary_unary_rpc_method_handler(
                    servicer.Lookup,
                    request_deserializer=symbol__pb2.LookupRequest.FromString,
                    response_serializer=symbol__pb2.LookupReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'srm.SymbolRegistry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('srm.SymbolRegistry', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SymbolRegistry(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Reserve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srm.SymbolRegistry/Reserve',
            symbol__pb2.ReserveRequest.SerializeToString,
            symbol__pb2.ReserveReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Claim(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srm.SymbolRegistry/Claim',
            symbol__pb2.ClaimRequest.SerializeToString,
            symbol__pb2.ClaimReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Lookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srm.SymbolRegistry/Lookup',
            symbol__pb2.LookupRequest.SerializeToString,
            symbol__pb2.LookupReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
